import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ReactElement } from 'react'
import { I18nProviderClient } from '@/locales/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  params,
  children,
}: {
  params: Promise<{ locale: string }>
  children: ReactElement
}) {
  const { locale } = await params
  
  return (
    <html lang={locale} suppressHydrationWarning>
    
        <I18nProviderClient locale={locale}>
          <body className={`antialiased`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </body>
        </I18nProviderClient>
      
    </html>
  )
}
